### ISSUE TITLE
MPU 6050 Not working

### ISSUE THREAD

**Issue by notthesinger** [notthesinger/ROV_Project#11]
Can't get any of my three MPU 6050 to work, one has before. Going to leave it out of the project, will update the rov in the future with it.

**Comment by grandpaku** [comment]
- [ ] add something

**Comment by notthesinger** [comment]
BOOM! I got it working, I was using what I believe is a depreciated version  (MPU-9250) which wasn't working but now I am using a slightly smaller MPU-6050 which is working using the MPU 6050 [library](https://github.com/jarzebski/Arduino-MPU6050) by `jarzebski`

**Comment by notthesinger** [comment]
So I am closing the issue due to it working :)
